### ISSUE TITLE
Zuweisung einer RPC Methode => Konfiguration

### ISSUE THREAD

**Issue by xat** [xat/contao-rpc#12]
Wir muessen da einen besseren weg finden als ueber mehrfach auswaehlbare Checkboxen. Entweder ueber radiobuttons oder pro Provider ein Select-field.

**Comment by mediabakery** [comment]
ich sehe da momentan nur ein eigenes Widget, dass das Radio Widget erweitert, damit es was mit den jetzigen options anfangen kann.

**Comment by mediabakery** [comment]
ARRG MCW schickt beim options_callback kein dc mit. Somit müssen wir uns doch leider was anderes ausdenken

**Comment by xat** [comment]
D.h. doch die Radiobutton Variante weiterverfolgen?

**Comment by mediabakery** [comment]
ja. Ich muss mal überlegen wie man das macht, damit es nicht geknufft wirkt ;)

**Comment by xat** [comment]
Bringts was anstatt der Radiobuttons Selects zu nutzen?

**Comment by mediabakery** [comment]
Glaube nicht wirklich. Ich glaube solch ein MultiRadio wäre schon die beste Lösung. Eigentlich wie eine MultiCheckbox nur eben mit Radios
