### ISSUE TITLE
Konfiguration: Allowed Authentifications.

### ISSUE THREAD

**Issue by xat** [xat/contao-rpc#4]
Die Konfiguration so erweitern, dass man angeben kann welche arten von Authentificationen erlaubt sind.

**Comment by mediabakery** [comment]
ist das nicht schon eigentlich vorhanden? Ich kann ja meine Häkchen setzen und somit sagen ob Admin, FE oder und BE darf

**Comment by mediabakery** [comment]
wir brauchen meiner Meinung nach die Parameter in der hasAccess Methode
https://github.com/xat/contao-rpc/blob/master/src/system/modules/rpc/classes/RpcEncryptionAccessor.php#L32

**Comment by xat** [comment]
Jup, ich habs mal eingebaut.

**Comment by xat** [comment]
Bzw. das hier ist das falsche issue :-) Encryption != Authentication

**Comment by xat** [comment]
Zu deiner ersten Frage:

Ne, ich mein mit diesem Issue hier, dass man festlegen kann welche arten von Authentifizierungen gestattet sein sollen.
D.h. im prinzip 3 Checkboxen: Allow Apikey Authentication, Allow Hash Authentication und Allow Credentials Authentication. 
Oder meinst du das ist nicht notwendig?

**Comment by mediabakery** [comment]
hey, 
ah jetzt ja. Verstehe und sorry für die falsche Einordnung gestern abend.
Kann man überlegen, wobei in meinem aktuellen Fall ja der erste Login mit User/Password passiert und ab dann mit Hash.

**Comment by xat** [comment]
Ich werd das einfach mal bauen.
