### ISSUE TITLE
tl_settings: Default Provider

### ISSUE THREAD

**Issue by xat** [xat/contao-rpc#5]
In tl_settings sollte man einen default provider auswaehlen koennen. Dieser wird verwendet wenn ein
RPC Request verschickt wurde ohne dem POST-Feld "provider".

**Comment by xat** [comment]
Bin mir gerade nicht mehr so sicher ob wir das unbedingt benoetigen. Es muessen ja auch jedesmal andere felder wie zum Beispiel der hash etc uebermittelt werden. Und eigentlich machts schon Sinn wenn der User bei seiner Anfrage den Provider immer mit angibt, selbst wenns nur einen registrierten Provider hat.

Es koennte ja sein, dass es am Anfang nur einen Provider hat und irgendwann spaeter mal einer dazu kommt. Auch wuerde die Aenderung des Default Providers immer nach sich ziehen dass die RPC Clients upgedated werden muessten die sich z.b. davor darauf verlassen haben, dass der default Provider 'json' entspricht. Wenn der Provider hingegen bei jedem Request mit angegeben wird dann signalisiert der RPC Client klar und deutlich welcher Provider verwendet werden soll.

Von daher close ich dieses Ticket jetzt.

**Comment by mediabakery** [comment]
stimme dir zu
