### ISSUE TITLE
ENCRYPTIONKEY Generator

### ISSUE THREAD

**Issue by xat** [xat/contao-rpc#7]
Der ENCRYPTIONKEY den man bei Benutzern/Members einstellen kann sollte ueber einen Button generiert werden koennen.

**Comment by mediabakery** [comment]
Done: feb8af41bd41bdc4602716ea949c4cb38443b0ac

**Comment by xat** [comment]
Die Extension ist sehr nice geworden :-)

Wenn die nicht vorhanden ist bekommt man ein "Missing Class" Error wenn man ein User/Member im backend editieren will. Ich hab daher die Extension mal als 'required' in der Readme umbenannt.
