### ISSUE TITLE
IRpcAccessor refactoren

### ISSUE THREAD

**Issue by xat** [xat/contao-rpc#8]
hasAccess() und abort() zusammen mergen in eine neue Methode, z.b. accessState().
Diese methode hat dann 3 Rueckgabewerte: ALLOW, SKIP, DENY

**Comment by xat** [comment]
Wie im IRC besprochen: Wir bauens nochmal so um, dass bei einem deny eine Exception geworfen wird. Diese kann dann gleichzeitig als Fehlerkanal verwendet werden um dem User ein Feedback zu geben.

**Comment by mediabakery** [comment]
scheint nicht die Exception Nachricht zurückzugeben.
Beispiel SSL
es ist ein Doppelter Fehler. throw new Exception kommt zumindest beim ssl nach return false. Hatte es geändert, jedoch wird die neue Fehlermelung nicht als Error gesetzt.

**Comment by xat** [comment]
Hmm, wie meinst du das mit "doppelter fehler" genau?
Bei den Tests ist ein SSL Test dabei ( https://github.com/xat/contao-rpc/blob/master/test/RpcTest.php#L361 ) 
der liefert bei mir das korrekte Resultat.

hasAccess return false entspricht jetzt SKIP
hasAccess return true entspricht ALLOW
hasAccess throws ERpcAccessorException entspricht DENY mit Fehlermeldung.

**Comment by mediabakery** [comment]
dann war es sicher ein Problem bei mir. Ich teste es noch mal später und sage Bescheid.
